name: push-to-nfs
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: '16'

      - working-directory: ./src/twinleaf
        run: npm install

      - working-directory: ./src/twinleaf
        run: npm run build

      - run: cp -r src/twinleaf/build twinleaf/

      - uses:  lemonarc/jekyll-action@master

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "_site"
          target: "/home/public"
          strip_components: 1
